---
# Debian
# Install Zabbix agent

- name: "Install zabbix agent"
  package:
    name: zabbix-agent
    state: present

- name: "Ensure /etc/zabbix/zabbix_agentd.d directory exists"
  file:
        path: /etc/zabbix/zabbix_agentd.d
        state: directory
        mode: 0755
        group: zabbix
  notify:
        - restart zabbix-agent
