---
# Common plays for every nodes
# Load variables
- name: "Set OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"
#  with_first_round:
#          - "{{ ansible_os_family }}.yml"

# Install Zabbix agent

- name: "Install agent for SUSE"
  include: "Suse.yml"
  when:
          - ansible_os_family == "Suse"

- name: "Install agent for Debian"
  include: "Debian.yml"
  when:
          - ansible_os_family == "Debian"
          
- name: "Copy Zabbix agent config"
  template: 
          src: zabbix_agentd.conf.j2 
          dest: "/etc/zabbix/{{ zabbix_agent_conf  }}"
  notify:
                  - restart zabbix-agent

# Disk performance monitoring files
- name: "Copy Zabbix Disk info templates config"
  copy: 
        src: userparameter_diskstats.conf 
        dest: /etc/zabbix/zabbix_agentd.d/userparameter_diskstats.conf
        group: zabbix

- name: "Copy Zabbix Disk info template script and make it executable"
  copy: 
        src: lld-disks.py 
        dest: /usr/local/bin/lld-disks.py
        mode: 0755
        group: zabbix

- name: "Make sure zabbix-agent service is running"
  service:
        name: "{{ zabbix_agent_service }}"
        state: started
        enabled: yes
