---
# Suse
# Install Zabbix agent

# To avoid ansible inability to parse .repo files we remove repo first
- name: "Remove old repo"
  zypper_repository:
        name: "server_monitoring"
        state: absent

- name: "Add Zabbix repositories for SUSE"
  zypper_repository:
        repo: 'http://download.opensuse.org/repositories/server:/monitoring/SLE_12_SP1/server:monitoring.repo'
        auto_import_keys: yes
        runrefresh: yes
        state: present

- name: "Install zabbix agent"
  package:
    name: zabbix-agent
    state: present

- name: "Ensure /etc/zabbix/zabbix_agentd.d directory exists"
# On SLES 12 you need to create it
  file:
        path: /etc/zabbix/zabbix_agentd.d
        state: directory
        mode: 0755
        group: zabbix
  notify:
        - restart zabbix-agent
